### ISSUE TITLE
Cannot delete-generations: no such bootloader

### ISSUE THREAD

**Issue by simendsjo** [giuliano108/guix-packages#10]
```
$ sudo guix system delete-generations --no-bootloader
accepted connection from pid 947, user root
deleting /var/guix/profiles/system-1-link
guix system: error: dummybootloader: no such bootloader
```

Great guide! Got a working system for the most part, but have a speed bump related to WSL2 and corporate firewall settings that require me to downgrade to WSL1. Unable to convert because I hit a hard-link bug in WSL, and I'm unable to remove those packages because of this issue.

Ref https://github.com/microsoft/WSL/issues/4457

**Comment by giuliano108** [comment]
The `dummybootloader` hack I'm using was definitely a bad idea, I'll remove that in the next version of the guide.

In the meantime you can try replacing `dummybootloader` with `grub` in `/var/guix/profiles/system/parameters`. When I did that, `delete-generations` worked for me.
