### ISSUE TITLE
wsl -d Guix --exec /busybox sh not working

### ISSUE THREAD

**Issue by devmsv** [giuliano108/guix-packages#11]
I still get the following error:

```
[ 1116.513850] EXT4-fs (sdc): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered [ 1116.540224] init: (1) ERROR: ConfigApplyWindowsLibPath:2129: open /etc/ld.so.conf.d/ld.wsl.conf [ 1116.540230] failed 2 [ 1116.541592] init: (1) ERROR: ConfigUpdateInformation:2727: creat /etc/hostname failed: 2 [ 1116.541602] init: (1) ERROR: ConfigUpdateInformation:2761: creat /etc/hosts failed 2 [ 1116.541985] init: (2) ERROR: UtilCreateProcessAndWait:486: /bin/mount failed with 2 [ 1116.542261] init: (1) ERROR: UtilCreateProcessAndWait:501: /bin/mount failed with status 0x [ 1116.542267] ff00 [ 1116.542282] init: (1) ERROR: ConfigMountFsTab:2184: Processing fstab with mount -a failed. [ 1116.544699] init: (3) ERROR: UtilCreateProcessAndWait:486: /bin/mount failed with 2
```

**Comment by giuliano108** [comment]
Did you get to the point where you have to run:

```
 /busybox cp /busybox /bin/mount
```

?

Or you don't get a Linux prompt after typing:

```
wsl -d guix --exec /busybox sh
```

?

I've finally got round to updating/testing `Guix-on-WSL2.md` for Guix 1.3.0 . Everything seems to work fine in my case...

**Comment by devmsv** [comment]
I didn't even get the bash prompt.

I have manage to installed mixing resources from you and:
 minikN wsl.org
 vldn-dev/guix-infect.sh

Thanks

El 23 de febrero de 2022 23:40:39 UTC, Giuliano Cioffi ***@***.***> escribió:
>Did you get to the point where you have to run:
>
>```
> /busybox cp /busybox /bin/mount
>```
>
>?
>
>Or you don't get a Linux prompt after typing:
>
>```
>wsl -d guix --exec /busybox sh
>```
>
>?
>
>I've finally got round to updating/testing `Guix-on-WSL2.md` for Guix 1.3.0 . Everything seems to work fine in my case... 
>


- - -
Sent from a phone, apologies for poor formatting.

**Comment by vitaliel** [comment]
Hi,

It did not work for me too, but after fixing permissions for `busybox` before making rootfs.tar.  it worked.
```
chmod +x busybox
```

**Comment by giuliano108** [comment]
Thanks @vitaliel for commenting. Yes, `busybox` not being executable might cause the issue as reported.
