### ISSUE TITLE
Trouble with docker config on WSL2

### ISSUE THREAD

**Issue by shader** [giuliano108/guix-packages#5]
Hello, I'm using your directions to run GuixSD on WSL2, and pretty much everything is working very well; thanks for publishing your guide!

However, I tried integrating some pieces from your wsl-config-docker.scm as an example for getting docker to work, and got the following error:

`error: (shepherd-service-type (quote dummy-networking) (const (shepherd-service (documentation "Provide loopback and networking without actually doing anything.") (provision (quote (loopback networking))) (start (gexp (const #t))))) #f): source expression failed to match any pattern`

I presume the error has to do with this section here (copied from mine):

```
(define dummy-networking-service-type
  (shepherd-service-type
    'dummy-networking
    (const (shepherd-service
            (documentation "Provide loopback and networking without actually doing anything.")
            (provision '(loopback networking))
            (start #~(const #t))))
    #f))
```

It's pretty much at the beginning of the file and looks the same as yours, so I'm not sure what the problem is.

My preamble is:
```
(use-modules
 (gnu)
 (gnu services)
 (gnu system linux-container)
 (gnu services shepherd)
 (guix profiles)
 (guix packages)
 (srfi srfi-1))

(use-service-modules base networking ssh desktop xorg dbus docker)
(use-package-modules emacs shells xorg fonts certs ssh bash base linux)
```

And I only have one other define before that one (for listing a bunch of fonts), which has worked before.

Any ideas?

**Comment by giuliano108** [comment]
> Any ideas?

I don't, sorry. :( Did you fix the issue in the end?

**Comment by shader** [comment]
I finally fixed it today; I think the code for service definitions must have changed.
Based on your dummy-networking service code, I wrote the following:

``` scheme
(define dummy-networking-service
  (const (list (shepherd-service
                (documentation "Provide loopback and networking without actually doing anything.")
                (provision '(loopback networking))
                (start #~(const #t))))))

(define dummy-networking-service-type
  (service-type
   (name 'dummy-networking)
   (extensions
    (list (service-extension shepherd-root-service-type dummy-networking-service)))
   (default-value '())))
```

I don't know if that's the best solution, but it works for me. I don't think I changed any of the rest of the docker-related code, but it's been a while.

**Comment by giuliano108** [comment]
Thanks for the workaround, closing.
